model_list : 
    - vit_pe_spatial_large_patch14_448.fb
    - convnextv2_base.fcmae_ft_in22k_in1k_384
    - vit_base_patch16_rope_mixed_ape_224.naver_in1k
    - vit_base_r50_s16_224.orig_in21k
    - vit_pe_core_large_patch14_336.fb
    - vit_base_patch14_dinov2.lvd142m
data_name : shapespark
save: True
local: True
